test(integration): fix racy URL construction by preventing double `?`
It's buggy to add a URL param by appending `?param` as this requires the URL to not end in ? or have other params set.

This caused flakes in tests as we automatically add trailing `?`. Tests would pass when playwright was faster than the addition of the `?` - but sometimes playwright was fast enough causing failures.

I spotted this by looking at playwright trace and seeing the URL being `http://localhost:3000/dummy-organism-with-files/submission/6/released??column_submissionId=true`

Now, we construct the full URL with params upfront or safely add extra params using a helper `setUrlParamsAndGoTo`

This fixes this test failure (or at least one way this would show up sporadically):

```
1) [firefox-without-dep] › tests/specs/features/file-sharing.spec.ts:102:5 › bulk revise 2 seqs with files

    Test timeout of 300000ms exceeded.

    Error: page.reload: Test timeout of 300000ms exceeded.
    Call log:
      - waiting for navigation until "load"

       at pages/search.page.ts:221

      219 |     async waitForSequences(role: 'link' | 'cell', name: string | RegExp) {
      220 |         while (!(await this.page.getByRole(role, { name: name }).isVisible())) {
    > 221 |             await this.page.reload();
          |                             ^
      222 |             await this.page.waitForTimeout(2000);
      223 |         }
      224 |     }
```