fix(deployment): default k3s image and `--k3s-image` argument in `deploy.py` (#6151)
I encountered an issue running `./deploy.py cluster --dev` and
`./deploy.py helm --dev` as-is. When running `./deploy.py helm --dev`, I
would get:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "compression-middleware" namespace: "" from "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "redirect-middleware" namespace: "" from "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "redirect-www-middleware" namespace: "" from "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "cors-all-origins" namespace: "" from "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
...
```

It turns out this was because the `k3d cluster create` command does not
specify the k3s image, and was installing a version of k3s that uses
traefik v3 rather than v2. K3s version 1.32 and above installs traefik
v3 by default: https://docs.k3s.io/upgrades#version-specific-caveats .

This PR adds a `--k3s-image` argument for `deploy.py cluster`, with the
image defaulting to
[rancher/k3s:v1.31.14-k3s1](https://hub.docker.com/r/rancher/k3s/tags?name=v1.31)
which resolves the helm issue. The user can also choose to use a
different image if they want to.

I'm not really aware of where this deployment script is used, so I am
curious if anyone already encountered this issue (I saw there is an
issue open for upgrading traefik: #6014).

### PR Checklist
- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by appropriate, automated
tests.
- [ ] Any manual testing that has been done is documented (i.e. what
exactly was tested?)

🚀 Preview: Add `preview` label to enable