chore(e2e): deflake known rare console error about CORS policy
Rare console errors that are not due to clear underlying problems. Possibly related to LAPIS or SILO dropping requests when switching to new dataVersion.

Console errors like this will no longer fail reducing flakiness:

```
Error: Unexpected console error: Access to XMLHttpRequest at 'http://10.1.1.126:8080/ebola-sudan/sample/aggregated' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```