fix(prepro): nextclade dataset tag conversion error (#5614)
resolves #

### Screenshot
When testing on PPX I see this error caused by
https://github.com/loculus-project/loculus/pull/5552 that I sadly missed
(string is converted to a list)- this should resolve the bug:

```
INFO:loculus_preprocessing.nextclade:Downloading Nextclade dataset: ['nextclade3', 'dataset', 'get', '--name=nextstrain/rsv/a/EPI_ISL_412866', '--server=https://data.clades.nextstrain.org/v3', '--output-dir=/tmp/tmp6frl2wtu/main', '-', '-', 't', 'a', 'g', '=', '2', '0', '2', '5', '-', '0', '8', '-', '2', '5', '-', '-', '0', '9', '-', '0', '0', '-', '3', '5', 'Z']
error: unexpected argument '-' found
```

### PR Checklist
- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by appropriate, automated
tests.
- [ ] Any manual testing that has been done is documented (i.e. what
exactly was tested?)

🚀 Preview: Add `preview` label to enable