chore(deps-dev): bump to playwright with new firefox version (#7049)
Clone of https://github.com/loculus-project/loculus/pull/7007 to see if
Firefox integration test flakiness can be addressed.

Dependabot is trying to bump playwright from 1.61.1 to 1.62.1, which has
Firefox version 153.0 (was 151.0 before:
https://github.com/microsoft/playwright/releases).

The integration test for Firefox failed repeatedly and unpredictably on
that branch on testing steps that create a new user through the Auth
page, specifically when trying to check the 'I agree' check box
(screenshots below). There is a playwright issue where people report
clicking checkboxes in playwright as a source of flakiness (though not
all exactly the same problem, see
https://github.com/microsoft/playwright/issues/13470)

This PR wraps the `this.page.getByLabel('I agree').check()` in an
`expect(...).toPass()` so it retries. While this does seem to resolve
flakiness, the underlying cause is still not clear to me. Especially
because we have different checkboxes that are `check()`-ed without
retrying in the integration tests where this issue doesn't arise
(although those are not in the keycloakify page).

### Screenshots

Error message in CI logs of
https://github.com/loculus-project/loculus/pull/7007

<img width="1312" height="502" alt="grafik"
src="https://github.com/user-attachments/assets/b60f9d6c-dd71-4cec-bd2c-66c64a9e9ba1"
/>

#### Playwright screenshots

Action:

<img width="944" height="499" alt="grafik"
src="https://github.com/user-attachments/assets/fa532c2e-052f-4579-ba68-ee60fbe862bb"
/>

The error logs:

```
Error: locator.check: Clicking the checkbox did not change its state
Call log:
  - waiting for getByLabel('I agree')
    - locator resolved to <input type="checkbox" id="termsAccepted" name="termsAccepted" aria-invalid="false" class="kcCheckboxInputClass"/>
  - attempting click action
    - waiting for element to be visible, enabled and stable
    - element is visible, enabled and stable
    - scrolling into view if needed
    - done scrolling
    - performing click action
    - click action done
    - waiting for scheduled navigations to finish
    - navigations have finished
 ```


Before:

<img width="165" height="47" alt="grafik" src="https://github.com/user-attachments/assets/d359c305-14bc-4b79-bd88-7ec0e3b74a0b" />


After:

<img width="165" height="47" alt="grafik" src="https://github.com/user-attachments/assets/487f6eb8-102e-4af4-9857-26efa1eeea40" />

(the blue square that's added seems to be locator added by playwright, not the actual page, `__playwright_target__ marker`)


### PR Checklist
- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by appropriate, automated tests.
- [ ] Any manual testing that has been done is documented (i.e. what exactly was tested?)

🚀 Preview: Add `preview` label to enable

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>