feat(ingest): only alert once for all revocations, do not raise error if multiple loculus accessions with same INSDC accession and at most one is not revoked (#4375)
resolves silly bug introduced in
https://github.com/loculus-project/loculus/pull/4177
```
File "/package/scripts/compare_hashes.py", line 250, in construct_submitted_dict
    raise ValueError(message)
ValueError: INSDC accession PP894723 has multiple loculus accessions: PP_001105M and PP_002Y9V1!
```
=> do not raise error if multiple loculus accessions link to the same
INSDC accession but one is revoked (only looked at one direction in
group before)

Also: currently we send a slack notification for every sequence we want
to revoke instead of one with all, this changes it to the later

### Screenshot

### PR Checklist
- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by appropriate, automated
tests.
- [ ] Any manual testing that has been done is documented (i.e. what
exactly was tested?)

🚀 Preview: https://ingest-revocation-fixes.loculus.org

---------

Co-authored-by: Cornelius Roemer <cornelius.roemer@gmail.com>