fix(taxonomy): Set check_same_thread to False for taxonomy service DB (#6214)
When monitoring the taxonomy-service logs on a PPX preview, I (very
rarely) saw the following internal server error:

```sh
INFO:     172.31.6.36:48592 - "GET /taxa/9397 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.14/site-packages/uvicorn/protocols/http/httptools_impl.py", line 416, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
...<146 lines>...
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140611877627584 and this is thread id 140611888133824.
```

Apparently, due to FastAPI's use of a threadpool it can sometimes happen
that one thread sets up a DB connection that gets used in another thread
(not familiar with the details). By default, Python's sqlite3 will then
error, since there's a risk of data corruption if multiple threads write
to a DB using the same connection (see `sqlite3.connect` documentation
here: https://docs.python.org/3/library/sqlite3.html)

Since our DB is fully read-only, we can set `check_same_thread=False` to
prevent these errors (which cause us to reject submitted sequences!)
while still benefiting from FastAPI's concurrency.

### PR Checklist
~- [] All necessary documentation has been adapted.~
- [x] The implemented feature is covered by appropriate, automated
tests.
~- [ ] Any manual testing that has been done is documented (i.e. what
exactly was tested?)~

🚀 Preview: Add `preview` label to enable