fix(deployment): Add retry logic for config processor (#7208)
resolves #

### Summary

I have encountered flakes a few times in Github CI for the `Dev server
test` workflow, due to GitHub pages being temporarily unavailable:

```
[2](https://github.com/loculus-project/loculus/actions/runs/33495729612/job/99817349521#step:7:13)
Traceback (most recent call last):
Processing /tmp/tmpuym2oeu1 to /home/runner/work/loculus/loculus/website/tests/config
  File "/home/runner/work/loculus/loculus/kubernetes/config-processor/config-processor.py", line 112, in <module>
Copied directory structure from /tmp/tmpuym2oeu1 to /home/runner/work/loculus/loculus/website/tests/config
    main(input_dir, output_dir, substitutions)
Downloading 97 unique URL(s) with 16 worker(s)
  File "/home/runner/work/loculus/loculus/kubernetes/config-processor/config-processor.py", line 97, in main
    process_files(output_dir, substitutions)
  File "/home/runner/work/loculus/loculus/kubernetes/config-processor/config-processor.py", line 78, in process_files
    downloaded_content = download_urls(collect_urls(output_dir))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/loculus/loculus/kubernetes/config-processor/config-processor.py", line 25, in download_urls
    return download_urls_with_workers(urls, max_workers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/loculus/loculus/kubernetes/config-processor/config-processor.py", line 46, in download_urls_with_workers
    raise ValueError(f"Problem downloading {error_details}")
ValueError: Problem downloading URL: https://alejandra-gonzalezsanchez.github.io/loculus-evs/enterovirus/evd68/VP3-evd68.fasta, Status Code: 503, Reason: Service Unavailable
Traceback (most recent call last):
Unprocessed config available in temp dir: /tmp/tmpuym2oeu1
Wrote config to /tmp/tmpuym2oeu1/backend_config.json
Wrote config to /tmp/tmpuym2oeu1/website_config.json
Wrote config to /tmp/tmpuym2oeu1/runtime_config.json
Wrote config to /tmp/tmpuym2oeu1/ingest-config.cchf.yaml
Wrote config to /tmp/tmpuym2oeu1/ingest-config.cchf-multi-ref.yaml
Wrote config to /tmp/tmpuym2oeu1/ingest-config.ebola-sudan.yaml
Wrote config to /tmp/tmpuym2oeu1/ingest-config.enteroviruses.yaml
Wrote config to /tmp/tmpuym2oeu1/ingest-config.west-nile.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.cchf.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.cchf-multi-ref.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.ebola-sudan.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.ebola-sudan.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.enteroviruses.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.not-aligned-organism.yaml
Wrote config to /tmp/tmpuym2oeu1/preprocessing-config.west-nile.yaml
  File "/home/runner/work/loculus/loculus/./deploy.py", line 579, in <module>
    main()
  File "/home/runner/work/loculus/loculus/./deploy.py", line 167, in main
    generate_configs(
  File "/home/runner/work/loculus/loculus/./deploy.py", line 423, in generate_configs
    run_command(
  File "/home/runner/work/loculus/loculus/./deploy.py", line 155, in run_command
    raise subprocess.SubprocessError(output.stderr)
subprocess.SubprocessError: None
```

I think adding some basic retry logic in the config processor should fix
this.

### Screenshot

### PR Checklist
- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by appropriate, automated
tests.
- [ ] Any manual testing that has been done is documented (i.e. what
exactly was tested?)

🚀 Preview: Add `preview` label to enable

---------

Co-authored-by: Cornelius Roemer <cornelius.roemer@gmail.com>
Co-authored-by: corneliusroemer-agent <cornelius.roemer+githubagent@gmail.com>